spring.application.name=sicrec

# ==========================
# POSTGRESQL
# ==========================

spring.datasource.url=jdbc:postgresql://localhost:5432/sicrec_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# ==========================
# JPA / HIBERNATE
# ==========================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==========================
# SERVER
# ==========================

server.port=8080

scopus.api.key=606340596a085694f2f289dd05969fd2
# API de búsqueda de artículos
scopus.base.url=https://api.elsevier.com/content/search/scopus

# API de información de revistas
scopus.serial.url=https://api.elsevier.com/content/serial/title

# ==========================
# CORREO ELECTRÓNICO
# ==========================

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=grupot900@gmail.com
spring.mail.password=jsbf xfps hale dgmq

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8