package uteq.edu.ec.crecuteq.provider;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.junit.jupiter.api.*;import org.junit.jupiter.api.io.TempDir;
import org.springframework.mock.web.MockMultipartFile;
import uteq.edu.ec.crecuteq.entity.CambridgeRevista;import uteq.edu.ec.crecuteq.repository.CambridgeRevistaRepository;import uteq.edu.ec.crecuteq.service.AuditoriaService;
import java.io.ByteArrayOutputStream;import java.net.URI;import java.net.http.HttpClient;import java.nio.file.Path;import java.time.Duration;import java.util.Optional;
import static org.junit.jupiter.api.Assertions.*;import static org.mockito.ArgumentMatchers.*;import static org.mockito.Mockito.*;
class CambridgeProviderTests{
 @TempDir Path temp;
 @Test void importaListaOficialConMonedasEIssn()throws Exception{var repo=vacio();var result=provider(repo).importar(excel());assertEquals(1,result.getRegistrosInsertados());verify(repo).save(argThat(r->"AAE".equals(r.getMnemonic())&&"2740".equals(r.getApcUsd())&&"1960".equals(r.getApcGbp())&&"20567405".equals(r.getEissnNormalizado())));}
 @Test void buscaPorEissnYExponePrecios(){var r=new CambridgeRevista();r.setMnemonic("AAE");r.setTitulo("Journal of Agricultural and Applied Economics");r.setIssn("1074-0708");r.setEissn("2056-7405");r.setModeloPublicacion("Gold OA");r.setApcUsd("2740");r.setApcGbp("1960");var repo=mock(CambridgeRevistaRepository.class);when(repo.findFirstByIssnNormalizadoOrEissnNormalizado(null,"20567405")).thenReturn(Optional.of(r));var info=provider(repo).buscar(null,null,"2056-7405").orElseThrow();assertEquals("cambridge",info.getProveedor());assertEquals("2740",info.getApc());assertEquals("1960",info.getDatosAdicionales().get("apcGbp"));}
 private CambridgeProvider provider(CambridgeRevistaRepository r){return new CambridgeProvider(r,mock(AuditoriaService.class),HttpClient.newHttpClient(),URI.create("https://cambridge.invalid/apc.xlsx"),Duration.ofSeconds(1),temp.resolve("hash"),false);}
 private CambridgeRevistaRepository vacio(){var r=mock(CambridgeRevistaRepository.class);when(r.findFirstByMnemonicIgnoreCase(anyString())).thenReturn(Optional.empty());return r;}
 private MockMultipartFile excel()throws Exception{try(var w=new XSSFWorkbook();var out=new ByteArrayOutputStream()){var s=w.createSheet("APC");var h=s.createRow(0);String[] main={"Mnemonic","Journal","Print ISSN","Online ISSN","New to Cambridge 2026","New to Cambridge 2027","HSS/STM","Open Access status","Gold OA APC","","","","","","","","","Gold OA CC licence options","URL"};for(int i=0;i<main.length;i++)h.createCell(i).setCellValue(main[i]);var sub=s.createRow(2);String[] prices={"GB £","GB £ Member Rate","US $","US $ Member Rate","EUR €","EUR € Member Rate","AUD","AUD Member Rate","APC Notes"};for(int i=0;i<prices.length;i++)sub.createCell(8+i).setCellValue(prices[i]);var row=s.createRow(3);Object[] v={"AAE","Journal of Agricultural and Applied Economics","1074-0708","2056-7405","","","HSS","Gold OA",1960,"",2740,"","","","","","","CC-BY","https://www.cambridge.org/core/product/identifier/AAE/type/JOURNAL"};for(int i=0;i<v.length;i++){if(v[i]instanceof Number n)row.createCell(i).setCellValue(n.doubleValue());else row.createCell(i).setCellValue(v[i].toString());}w.write(out);return new MockMultipartFile("archivo","cambridge.xlsx","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",out.toByteArray());}}
}
